Repository argoproj/argo-workflows, pull requests merged in 2020-11, with the labels that each got.

#4436 ci: Speed up e2e tests by 25%
  test/e2e/fixtures/e2e_suite.go
  test/e2e/fixtures/when.go
Labels: only-needs-a-rubber-stamp

#4437 chore: Update pull request template
  .github/pull_request_template.md
Labels: just-merge-it

#4132 fix(controller): Fix throttler. Fixes #1554 and #4081
  docs/workflow-controller-configmap.yaml
  workflow/controller/config_test.go
  workflow/controller/controller.go
  workflow/controller/controller_test.go
  workflow/sync/semaphore.go
  workflow/sync/throttler.go
  workflow/sync/throttler_test.go
Labels: epic/reliability

#4413 fix(controller): Trigger no of workflows based on available lock
  workflow/sync/semaphore.go
  workflow/sync/sync_manager_test.go
Labels: only-needs-a-rubber-stamp

#4465 refactor: Simplify grpcutil.TranslateError
  pkg/apiclient/error-translating-cluster-workflow-template-service-client.go
  pkg/apiclient/error-translating-cron-workflow-service-client.go
  pkg/apiclient/error-translating-workflow-service-client.go
  pkg/apiclient/error-translating-workflow-template-service-client.go
  util/grpc/errors.go
Labels: only-needs-a-rubber-stamp

#4459 chore(docs): Fix docgen
  Makefile
  docs/cli/argo.md
  docs/cli/argo_cron.md
  docs/cli/argo_cron_create.md
  docs/cli/argo_cron_delete.md
  docs/cli/argo_cron_get.md
  docs/cli/argo_cron_lint.md
  docs/cli/argo_cron_list.md
  docs/cli/argo_cron_resume.md
  docs/cli/argo_cron_suspend.md
  docs/cli/argo_server.md
  test/e2e/functional_test.go
Labels: just-merge-it, only-needs-a-rubber-stamp

#4547 fix(controller): Correct default port logic
  workflow/controller/controller.go
Labels: just-merge-it

#4569 chore: Updated stress test YAML
  test/e2e/stress/many-massive-workflows.yaml
Labels: just-merge-it, only-needs-a-rubber-stamp
