Repository argoproj/argo-workflows, pull requests merged in 2020-05, with the labels that each got.

#2854 feat(cli): Refactor `argo list --chunk-size` and add `argo archive list --chunk-size`. Fixes #2820
  cmd/argo/commands/archive/list.go
  cmd/argo/commands/get.go
  cmd/argo/commands/list.go
  go.mod
  test/e2e/cli_test.go
  test/e2e/cli_with_server_test.go
  util/printer/workflow-printer.go
  util/printer/workflow-printer_test.go
Labels: scalability

#2786 fix(argo-server)!: Implement missing instanceID code. Fixes #2780
  api/openapi-spec/swagger.json
  cmd/argo/commands/client/conn.go
  cmd/argo/commands/cron/create.go
  cmd/argo/commands/root.go
  cmd/argo/commands/submit.go
  persist/sqldb/workflow_archive.go
  pkg/apiclient/apiclient.go
  pkg/apiclient/argo-kube-client.go
  pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.pb.go
  pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto
  pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.swagger.json
  pkg/apiclient/cronworkflow/cron-workflow.pb.go
  pkg/apiclient/cronworkflow/cron-workflow.proto
  pkg/apiclient/cronworkflow/cron-workflow.swagger.json
  pkg/apiclient/workflow/workflow.pb.go
  pkg/apiclient/workflow/workflow.proto
  pkg/apiclient/workflow/workflow.swagger.json
  pkg/apiclient/workflowtemplate/workflow-template.pb.go
  pkg/apiclient/workflowtemplate/workflow-template.proto
  pkg/apiclient/workflowtemplate/workflow-template.swagger.json
  pkg/apis/workflow/v1alpha1/common.go
  pkg/apis/workflow/v1alpha1/generated.pb.go
  pkg/apis/workflow/v1alpha1/generated.proto
  server/apiserver/argoserver.go
  server/artifacts/artifact_server.go
  server/clusterworkflowtemplate/cluster_workflow_template_server.go
  server/clusterworkflowtemplate/cluster_workflow_template_server_test.go
  server/cronworkflow/cron_workflow_server.go
  server/cronworkflow/cron_workflow_server_test.go
  server/workflow/test_server_stream_test.go
  server/workflow/workflow_server.go
  server/workflow/workflow_server_test.go
  server/workflowtemplate/workflow_template_server.go
  server/workflowtemplate/workflow_template_server_test.go
  test/e2e/argo_server_test.go
  test/e2e/fixtures/persistence.go
  test/util/json.go
  test/util/yaml.go
  util/instanceid/service.go
  util/instanceid/service_test.go
  util/labels/labeler.go
  util/labels/labeler_test.go
  workflow/controller/config.go
  workflow/util/util.go
Labels: scalability

#2959 feat(ui): Render 2000+ nodes DAG acceptably.
  test/e2e/images/argosay/Dockerfile
  test/e2e/ui/ui-massive-workflow.yaml
  ui/src/app/archived-workflows/components/archived-workflow-details/archived-workflow-details.tsx
  ui/src/app/shared/components/resource-submit.tsx
  ui/src/app/shared/duration.ts
  ui/src/app/shared/examples.ts
  ui/src/app/shared/utils.ts
  ui/src/app/workflows/components/workflow-dag/graph/coffman-graham-sorter.ts
  ui/src/app/workflows/components/workflow-dag/graph/dfs-sorter.ts
  ui/src/app/workflows/components/workflow-dag/graph/graph.ts
  ui/src/app/workflows/components/workflow-dag/workflow-dag-render-options-panel.tsx
  ui/src/app/workflows/components/workflow-dag/workflow-dag.scss
  ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
  ui/src/app/workflows/components/workflow-details/workflow-details.scss
  ui/src/app/workflows/components/workflow-details/workflow-details.tsx
  ui/src/app/workflows/components/workflows-list/workflows-list.tsx
Labels: scalability

#2937 feat(controller)!: Updates the resource duration calculation. Fixes #2934
  config/config.go
  docs/resource-duration.md
  docs/workflow-controller-configmap.yaml
  manifests/quick-start-mysql.yaml
  manifests/quick-start-no-db.yaml
  manifests/quick-start-postgres.yaml
  manifests/quick-start/base/overlays/workflow-controller-configmap.yaml
  persist/sqldb/mocks/OffloadNodeStatusRepo.go
  persist/sqldb/mocks/WorkflowArchive.go
  pkg/apis/workflow/v1alpha1/workflow_types.go
  pkg/apis/workflow/v1alpha1/workflow_types_test.go
  ui/src/app/shared/duration.ts
  ui/src/app/shared/resources-duration.tsx
  ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
  ui/src/models/workflows.ts
  util/resource/duration.go
  util/resource/duration_test.go
  util/resource/summary.go
  workflow/controller/operator.go
  workflow/executor/mocks/ContainerRuntimeExecutor.go
Labels: enhancement

#2999 fix(events): Correct event API Version. Fixes #2994
  util/argo/audit_logger.go
  util/argo/audit_logger_test.go
Labels: bug

#3018 fix(ui): Displays command args correctly pre-formatted.
  ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
Labels: bug, ui

#2971 feat(ui): Enable CSP, HSTS, X-Frame-Options. Fixes #2760, #1376, #2761
  cmd/argo/commands/server.go
  server/apiserver/argoserver.go
  server/static/static.go
  ui/src/app/assets/fonts/Heebo-Regular.ttf
  ui/src/app/assets/styles/heebo.css
  ui/src/app/index.html
  ui/src/app/webpack.config.js
Labels: security

#3009 fix: Improve robustness of releases. Fixes #3004
  .circleci/config.yml
  Dockerfile
  Makefile
  docs/releasing.md
  ui/.yarnrc
Labels: bug

#3025 fix(executor): Save script results before artifacts in case of error. Fixes #1472
  cmd/argoexec/commands/wait.go
Labels: bug

#3023 fix(controller)!: Correctly format workflow.creationTimestamp as RFC3339. Fixes #2974
  workflow/controller/operator.go
  workflow/controller/operator_test.go
Labels: bug

#3024 fix(artifacts): Allow tar check to be ignored. Fixes #2140
  pkg/apis/workflow/v1alpha1/workflow_types.go
  pkg/apis/workflow/v1alpha1/workflow_types_test.go
  workflow/executor/executor.go
Labels: enhancement

#3047 fix(artifacts): Revert allow tar check to be ignored. Reverts #3024
  pkg/apis/workflow/v1alpha1/workflow_types.go
  pkg/apis/workflow/v1alpha1/workflow_types_test.go
  workflow/executor/executor.go
Labels: bug

#2941 fix(controller): Implement offloading for workflow updates that are re-applied. Fixes #2856
  Makefile
  persist/sqldb/explosive_offload_node_status_repo.go
  server/apiserver/argoserver.go
  server/artifacts/artifact_server.go
  server/workflow/workflow_server.go
  server/workflow/workflow_server_test.go
  test/e2e/argo_server_test.go
  test/e2e/cli_test.go
  test/e2e/cli_with_server_test.go
  test/e2e/fixtures/e2e_suite.go
  test/e2e/fixtures/given.go
  test/e2e/fixtures/then.go
  test/e2e/fixtures/when.go
  test/e2e/functional_test.go
  test/util/json.go
  util/json/json.go
  workflow/controller/config.go
  workflow/controller/controller.go
  workflow/controller/controller_test.go
  workflow/controller/operator.go
  workflow/controller/operator_persist_test.go
  workflow/controller/operator_test.go
  workflow/hydrator/fake/always.go
  workflow/hydrator/fake/always_test.go
  workflow/hydrator/fake/noop.go
  workflow/hydrator/hydrator.go
  workflow/hydrator/hydrator_test.go
  workflow/packer/packer.go
  workflow/packer/packer_test.go
  workflow/util/util.go
  workflow/util/util_test.go
Labels: bug

#3108 docs: Add Alibaba Cloud OSS to the list of supported artifacts
  README.md
Labels: blocked
