Repository argoproj/argo-workflows, pull requests merged in 2020-10, with the labels that each got.

#4217 fix: Revert "chore: try out pre-pushing linux/amd64 images and updating ma… Fixes #4216
  .github/workflows/docker-image.yml
  docs/releasing.md
Labels: P1, just-merge-it, only-needs-a-rubber-stamp

#4207 fix(controller): reduce withItem/withParams memory usage. Fixes #3907
  workflow/controller/dag.go
  workflow/controller/steps.go
Labels: bug

#4220 chore: Enahnce logging around pod failures
  workflow/controller/operator.go
Labels: only-needs-a-rubber-stamp

#4184 feat: Controller/server runAsNonRoot. Closes #1824
  Dockerfile.dev
  Makefile
  manifests/base/argo-server/argo-server-deployment.yaml
  manifests/base/workflow-controller/workflow-controller-deployment.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  manifests/quick-start-minimal.yaml
  manifests/quick-start-mysql.yaml
  manifests/quick-start-postgres.yaml
  test/e2e/manifests/mixins/argo-server-deployment.yaml
  test/e2e/manifests/mixins/workflow-controller-deployment.yaml
Labels: just-merge-it, only-needs-a-rubber-stamp, security

#4202 fix(controller): Support int64 for param value. Fixes #4169
  pkg/apis/workflow/v1alpha1/generated.pb.go
  pkg/apis/workflow/v1alpha1/int64orstr.go
  pkg/apis/workflow/v1alpha1/int64orstr_test.go
  pkg/apis/workflow/v1alpha1/workflow_types.go
  pkg/apis/workflow/v1alpha1/zz_generated.deepcopy.go
  server/event/dispatch/operation.go
  server/event/dispatch/operation_test.go
  test/e2e/cli_with_server_test.go
  test/e2e/functional_test.go
  util/printer/workflow-printer.go
  util/printer/workflow-printer_test.go
  workflow/common/util.go
  workflow/controller/cache_test.go
  workflow/controller/controller.go
  workflow/controller/operator.go
  workflow/controller/operator_test.go
  workflow/controller/operator_workflow_template_ref_test.go
  workflow/controller/steps.go
  workflow/controller/workflowpod.go
  workflow/controller/workflowpod_test.go
  workflow/executor/executor.go
  workflow/executor/executor_test.go
  workflow/executor/resource.go
  workflow/util/merge_test.go
  workflow/util/util.go
  workflow/util/util_test.go
  workflow/validate/validate.go
Labels: P1

#4227 docs: Reinstate swagger.md so docs can build.
  docs/swagger.md
Labels: just-merge-it, only-needs-a-rubber-stamp

#3558 feat(ui): Adds a report page which shows basic historical workflow metrics. Closes #3557
  ui/package.json
  ui/src/app/app.tsx
  ui/src/app/reports/components/report-container.tsx
  ui/src/app/reports/components/reports.tsx
  ui/src/app/reports/index.ts
  ui/src/app/shared/services/workflows-service.ts
  ui/src/app/workflows/components/workflow-steps/workflow-steps.scss
  ui/src/app/workflows/components/workflow-steps/workflow-steps.tsx
  ui/src/models/workflows.ts
  ui/yarn.lock
Labels: epic/metrics-monitoring-reporting

#4241 fix(ui): Fix bugs with DAG view. Fixes #4232 & #4236
  ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
Labels: just-merge-it, only-needs-a-rubber-stamp

#4248 fix(ui): Revert bad part of commit
  Makefile
  ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
Labels: just-merge-it, only-needs-a-rubber-stamp

#4225 feat(controller): Reduce reconcilliation time by exiting earlier.
  workflow/controller/workflowpod.go
Labels: epic/scaling, just-merge-it, only-needs-a-rubber-stamp

#4226 chore(api): Update swagger.json with Kubernetes v1.17.5 types. Closes #4204
  Makefile
  api/openapi-spec/swagger.json
  docs/fields.md
Labels: epic/unity, just-merge-it, only-needs-a-rubber-stamp

#4194 feat(controller): Track N/M progress. See #2717
  api/openapi-spec/swagger.json
  cmd/argo/commands/get.go
  cmd/argo/commands/get_test.go
  docs/fields.md
  docs/progress.md
  manifests/base/crds/full/argoproj.io_workflows.yaml
  mkdocs.yml
  pkg/apis/workflow/v1alpha1/generated.proto
  pkg/apis/workflow/v1alpha1/openapi_generated.go
  pkg/apis/workflow/v1alpha1/progress.go
  pkg/apis/workflow/v1alpha1/progress_test.go
  pkg/apis/workflow/v1alpha1/workflow_types.go
  test/e2e/progress_test.go
  ui/src/app/shared/services/workflows-service.ts
  ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
  ui/src/app/workflows/components/workflow-summary-panel.tsx
  ui/src/app/workflows/components/workflows-list/workflows-list.tsx
  ui/src/app/workflows/components/workflows-row/workflows-row.tsx
  ui/src/models/workflows.ts
  workflow/controller/operator.go
  workflow/controller/operator_concurrency_test.go
  workflow/controller/operator_test.go
  workflow/progress/updater.go
  workflow/progress/updater_test.go
Labels: epic/metrics-monitoring-reporting

#4251 docs: Add docs for `securityContext` and `emptyDir`. Closes #2239
  docs/empty-dir.md
  docs/security.md
  docs/workflow-executors.md
  docs/workflow-pod-security-context.md
  mkdocs.yml
Labels: executor/docker, executor/k8sapi, executor/kubelet, executor/pns, security

#4269 chore(controller): N/M progress fixes
  cmd/argo/commands/get.go
  pkg/apis/workflow/v1alpha1/generated.pb.go
Labels: just-merge-it, only-needs-a-rubber-stamp

#4276 test: Tidy up E2E tests
  test/e2e/argo_server_test.go
  test/e2e/cli_test.go
  test/e2e/fixtures/e2e_suite.go
  test/e2e/fixtures/then.go
  test/e2e/fixtures/when.go
  test/e2e/smoke/artifact-passing.yaml
Labels: just-merge-it, only-needs-a-rubber-stamp

#4255 feat(ui): Add a nudge for users who have not set their security context. Closes #4233
  ui/src/app/shared/components/cost-optimisation-nudge.tsx
  ui/src/app/shared/components/nudge.tsx
  ui/src/app/shared/components/security-nudge.tsx
  ui/src/app/workflows/components/workflow-details/workflow-details.tsx
  ui/src/models/workflows.ts
Labels: just-merge-it, only-needs-a-rubber-stamp, security

#4280 fix(ui): Ignore missing nodes in DAG. Fixes #4232
  ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
Labels: just-merge-it, only-needs-a-rubber-stamp

#4294 fix(controller): Patch rather than update cron workflows.
  workflow/cron/operator.go
  workflow/cron/operator_test.go
Labels: P2, bug

#4315 build: Refactor `codegen` to make target dependencies clearer
  .github/workflows/ci-build.yaml
  Makefile
  hack/crdgen.sh
  hack/generate-proto.sh
  hack/update-codegen.sh
  test/e2e/cron_test.go
Labels: epic/unity, just-merge-it, only-needs-a-rubber-stamp

#4295 docs: Add diagram
  .gitignore
  Makefile
  docs/architecture.md
  docs/assets/architecture-v2-5.png
  docs/assets/diagram.png
  go.mod
  go.sum
  hack/diagram/main.go
Labels: just-merge-it

#4284 docs: Update releasing guide
  docs/releasing.md
Labels: just-merge-it, only-needs-a-rubber-stamp

#4307 refactor: De-couple config
  .github/workflows/ci-build.yaml
  config/config.go
  config/controller.go
  config/controller_test.go
  persist/sqldb/sqldb.go
  server/apiserver/argoserver.go
  server/apiserver/config.go
  test/e2e/fixtures/persistence.go
  workflow/controller/config.go
  workflow/controller/config_test.go
  workflow/controller/controller.go
  workflow/metrics/metrics.go
  workflow/metrics/metrics_test.go
  workflow/metrics/server.go
Labels: epic/unity

#4253 feat(executor): Wait for termination using pod watch for PNS and K8SAPI executors.
  .github/workflows/ci-build.yaml
  Makefile
  docs/empty-dir.md
  test/e2e/fixtures/e2e_suite.go
  test/e2e/fixtures/persistence.go
  test/e2e/images/argosay/v2/main/argosay.go
  test/e2e/smoke/runasnonroot-workflow.yaml
  test/e2e/smoke_test.go
  workflow/executor/common/wait/wait.go
  workflow/executor/k8sapi/client.go
  workflow/executor/k8sapi/k8sapi.go
  workflow/executor/pns/pns.go
  workflow/validate/validate.go
Labels: epic/scaling, executor/k8sapi, executor/kubelet, executor/pns, security

#4363 build: Remove `vendor` at end of `codegen`
  Makefile
Labels: just-merge-it, only-needs-a-rubber-stamp

#4376 fix: Fix intstr nil dereference
  workflow/controller/operator.go
  workflow/validate/validate.go
Labels: only-needs-a-rubber-stamp

#4350 fix(server): Download artifacts from UI. Fixes #4338
  Makefile
  manifests/base/argo-server/argo-server-deployment.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  manifests/quick-start-minimal.yaml
  manifests/quick-start-mysql.yaml
  manifests/quick-start-postgres.yaml
  server/artifacts/artifact_server.go
Labels: regression

#4396 fix(controller): Fix estimation of duration for DAGs. Fixes #4386
  workflow/controller/estimation/estimator.go
  workflow/controller/estimation/estimator_test.go
Labels: just-merge-it, only-needs-a-rubber-stamp

#4397 fix(ui): Ignore running workflows in report. Fixes #4387
  ui/src/app/reports/components/reports.tsx
Labels: just-merge-it, only-needs-a-rubber-stamp

#4404 ci: Split e2e tests to make them faster
  .github/workflows/ci-build.yaml
  .golangci.yml
  Makefile
  test/e2e/argo_server_test.go
  test/e2e/cli_test.go
  test/e2e/cli_with_server_test.go
  test/e2e/client.go
  test/e2e/http_logger.go
Labels: just-merge-it, only-needs-a-rubber-stamp

#4399 fix: Use correct template when processing metrics
  workflow/controller/operator.go
Labels: only-needs-a-rubber-stamp
