Repository argoproj/argo-workflows, pull requests merged in 2020-02, with the labels that each got.

#2122 feat: Implemented open default browser in local mode
  Gopkg.lock
  cmd/argo/commands/server.go
  server/apiserver/argoserver.go
Labels: argo-server, enhancement

#2193 chore: Move info.proto et al to correct package
  pkg/apiclient/info/info.pb.go
  pkg/apiclient/info/info.pb.gw.go
  pkg/apiclient/info/info.proto
  pkg/apiclient/info/info.swagger.json
  server/apiserver/argoserver.go
  server/info/info_server.go
Labels: tech debt

#2194 test: Invoke tests using s.T()
  test/e2e/argo_server_test.go
  test/e2e/cli_test.go
  test/e2e/cli_with_server_test.go
  test/e2e/cron_test.go
  test/e2e/fixtures/e2e_suite.go
  test/e2e/functional_test.go
  test/e2e/smoke_test.go
  test/e2e/workflow_template_test.go
Labels: tech debt

#2213 fix: Remove quotes from UI
  ui/src/app/shared/services/workflows-service.ts
Labels: bug, regression

#2214 test: Correctly report e2e test diagnostics
  test/e2e/fixtures/e2e_suite.go
Labels: bug

#2215 build: Fix ARGO_TOKEN
  Makefile
Labels: tech debt

#2097 feat: upgrade to Go 1.13. Closes #1375
  .circleci/config.yml
  .gitignore
  Dockerfile
  Dockerfile.dev
  Gopkg.lock
  Gopkg.toml
  Makefile
  go.mod
  go.sum
  hack/generate-proto.sh
  hack/update-codegen.sh
  hack/update-openapigen.sh
  hack/verify-codegen.sh
  pkg/apiclient/cronworkflow/cron-workflow.pb.go
  pkg/apiclient/cronworkflow/cron-workflow.proto
  pkg/apiclient/info/info.pb.go
  pkg/apiclient/info/info.proto
  pkg/apiclient/workflow/workflow.pb.go
  pkg/apiclient/workflow/workflow.proto
  pkg/apiclient/workflowarchive/workflow-archive.pb.go
  pkg/apiclient/workflowarchive/workflow-archive.proto
  pkg/apiclient/workflowtemplate/workflow-template.pb.go
  pkg/apiclient/workflowtemplate/workflow-template.proto
  workflow/cron/controller.go
  workflow/cron/operator.go
  workflow/metrics/collector.go
Labels: do not merge yet

#2234 fix(offload): Fix bug which deleted completed workflows. Fixes #2233
  persist/sqldb/offload_node_status_repo.go
  server/apiserver/argoserver.go
  test/e2e/fixtures/persistence.go
  test/e2e/manifests/mysql.yaml
  test/e2e/manifests/mysql/overlays/workflow-controller-deployment.yaml
  test/e2e/manifests/no-db.yaml
  test/e2e/manifests/no-db/overlays/workflow-controller-deployment.yaml
  test/e2e/manifests/postgres.yaml
  test/e2e/manifests/postgres/overlays/workflow-controller-deployment.yaml
  workflow/controller/config_controller.go
  workflow/controller/controller.go
Labels: bug

#2271 fix: Fixes double logging in UI. Fixes #2270
  ui/src/app/shared/services/requests.ts
Labels: ui

#2303 chore(cli): Clean-up code. Closes #2117
  cmd/argo/commands/client/conn.go
  cmd/argo/commands/common.go
  cmd/argo/commands/server.go
  pkg/apiclient/argo-server-client.go
Labels: tech debt
