Repository argoproj/argo-workflows, pull requests merged in 2020-12, with the labels that each got.

#4625 fix: Fix TestCleanFieldsExclude
  util/fields/fields.go
  util/fields/fields_test.go
Labels: only-needs-a-rubber-stamp

#4682 test: Add test for aggrgate parameters
  docs/fields.md
  examples/parameter-aggregation-dag.yaml
  workflow/controller/operator.go
  workflow/controller/operator_test.go
Labels: only-needs-a-rubber-stamp

#4698 fix(controller): Increase default EventSpamBurst in Event-recorder
  workflow/events/event_recorder_manager.go
Labels: only-needs-a-rubber-stamp

#4704 ci: Pin kustomize version
  Makefile
Labels: just-merge-it, only-needs-a-rubber-stamp

#4688 fix(test): Fixed Flaky e2e tests TestSynchronizationWfLevelMutex and TestResourceTemplateStopAndTerminate/ResourceTemplateStop
  test/e2e/cli_test.go
Labels: only-needs-a-rubber-stamp

#4715 fix(controller): Fixed RBAC on leases
  manifests/cluster-install/workflow-controller-rbac/workflow-controller-role.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  manifests/namespace-install/workflow-controller-rbac/workflow-controller-role.yaml
  manifests/quick-start-minimal.yaml
  manifests/quick-start-mysql.yaml
  manifests/quick-start-postgres.yaml
Labels: only-needs-a-rubber-stamp

#4708 fix(ui): Fix "Using Your Login". Fixes #4707
  ui/src/app/userinfo/components/cli-help.tsx
Labels: just-merge-it, only-needs-a-rubber-stamp

#4721 chore: Update stress test files.
  manifests/quick-start-minimal.yaml
  manifests/quick-start-mysql.yaml
  manifests/quick-start-postgres.yaml
  manifests/quick-start/base/artifact-repositories-configmap.yaml
  test/e2e/stress/many-massive-workflows.yaml
Labels: just-merge-it, only-needs-a-rubber-stamp

#4722 feat(controller): Add Prometheus metric: `workflow_ttl_queue`
  workflow/ttlcontroller/ttlcontroller.go
Labels: epic/metrics-monitoring-reporting

#4725 feat(controller): Pod deletion grace period. Fixes #4719
  workflow/controller/operator.go
  workflow/metrics/pod_missing_metric.go
  workflow/metrics/server.go
Labels: epic/scaling

#4736 feat(controller): Enhanced TTL controller scalability
  cmd/workflow-controller/main.go
  docs/scaling.md
  test/e2e/fixtures/then.go
  test/e2e/functional_test.go
  workflow/controller/controller.go
  workflow/metrics/metrics_test.go
  workflow/ttlcontroller/ttlcontroller.go
  workflow/ttlcontroller/ttlcontroller_test.go
Labels: epic/scaling

#4742 fix(controller): Requeue when the pod was deleted. Fixes #4719
  workflow/controller/operator.go
Labels: bug

#4741 fix(controller): Fixes resource version misuse. Fixes #4714
  cmd/argo/commands/wait.go
  cmd/argo/commands/watch.go
  server/workflow/workflow_server.go
  ui/src/app/shared/services/requests.ts
  ui/src/app/workflows/components/workflow-details/workflow-details.tsx
  util/logs/workflow-logger.go
Labels: bug

#4739 fix(ui): Remove unused Heebo files. Fixes #4730
  ui/src/app/assets/styles/heebo.css
  ui/src/app/index.html
  ui/src/app/workflows/components/workflow-dag/workflow-dag.scss
Labels: only-needs-a-rubber-stamp

#4758 test: Improved e2e test robustness
  test/e2e/argo_server_test.go
  test/e2e/cli_test.go
  test/e2e/fixtures/given.go
  test/e2e/fixtures/when.go
  test/e2e/functional_test.go
  test/e2e/testdata/sleepy-workflow.yaml
Labels: only-needs-a-rubber-stamp

#4728 refactor(controller): Enhanced pod clean-up scalability
  cmd/workflow-controller/main.go
  pkg/apis/workflow/v1alpha1/workflow_types.go
  test/e2e/fixtures/then.go
  test/e2e/pod_cleanup_test.go
  test/e2e/testdata/sleepy-retry-on-error-workflow.yaml
  workflow/controller/controller.go
  workflow/controller/controller_test.go
  workflow/controller/operator.go
  workflow/controller/pod_cleanup_key.go
Labels: epic/scaling

#4757 fix(controller): Support default database port. Fixes #4756
  config/config.go
  config/config_test.go
  persist/sqldb/sqldb.go
Labels: bug, regression

#4726 feat(controller): Rate-limit workflows. Closes #4718
  workflow/controller/controller.go
  workflow/controller/controller_test.go
  workflow/controller/operator.go
  workflow/controller/rate_limiters.go
  workflow/controller/workflowpod.go
Labels: epic/scaling

#4775 fix(server): Do not silently ignore sso secret creation error
  server/auth/sso/sso.go
Labels: bug

#4779 test: Fix `TestDeletingRunningPod`. Fixes #4778
  test/e2e/functional_test.go
Labels: only-needs-a-rubber-stamp
