Repository argoproj/argo-workflows, pull requests merged in 2021-01, with the labels that each got.

#4864 fix(controller): Add matrix tests for node offload disabled. Resolves #2333
  .github/workflows/ci-build.yaml
  Makefile
Labels: just-merge-it

#4866 build: sudoless `make codegen -B`
  Makefile
Labels: just-merge-it, only-needs-a-rubber-stamp

#4890 fix(ui): Show non-pod nodes
  ui/src/app/shared/components/graph/graph-panel.tsx
Labels: only-needs-a-rubber-stamp

#4896 build: on a dev branch automatically start the UI
  .github/workflows/ci-build.yaml
  Makefile
  Procfile
  workflow/controller/controller_test.go
  workflow/controller/operator_test.go
  workflow/controller/workflowpod_test.go
Labels: only-needs-a-rubber-stamp

#4895 fix(ui): UI bug fixes
  ui/src/app/event-flow/components/event-flow-details/event-flow-page.tsx
  ui/src/app/shared/list-watch.ts
  ui/src/app/shared/retry-observable.ts
  ui/src/app/shared/retry-watch.ts
  ui/src/app/shared/services/info-service.ts
  ui/src/app/userinfo/components/cli-help.tsx
  ui/src/app/widgets/widget-gallery.tsx
  ui/src/app/workflows/components/workflow-creator.tsx
  ui/src/app/workflows/components/workflow-details/workflow-details.tsx
  ui/yarn.lock
Labels: only-needs-a-rubber-stamp

#4847 fix: Mutex not being released on step completion
  .gitignore
  workflow/controller/operator.go
  workflow/controller/operator_concurrency_test.go
  workflow/sync/sync_manager.go
Labels: only-needs-a-rubber-stamp

#4906 fix(ui): Fix workflow refresh bug
  ui/src/app/workflows/components/workflow-details/workflow-details.tsx
Labels: only-needs-a-rubber-stamp

#4902 build: Inline Argo Events CRD URLs to reduce build errors
  test/e2e/manifests/minimal/kustomization.yaml
Labels: only-needs-a-rubber-stamp

#4926 build: Faster `make start`, faster smoke jobs
  .golangci.yml
  Makefile
  test/e2e/argo_server_test.go
  test/e2e/cron_test.go
  test/e2e/manifests/mysql/kustomization.yaml
  test/e2e/metrics_test.go
  test/e2e/smoke_test.go
  ui/src/app/webpack.config.js
Labels: only-needs-a-rubber-stamp

#4977 fix: Use button in side panel links
  ui/src/app/shared/components/icon.ts
  ui/src/app/shared/components/links.tsx
  ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
Labels: only-needs-a-rubber-stamp
