Repository argoproj/argo-workflows, pull requests merged in 2023-08, with the labels that each got.

#11426 fix(server): don't grab SAs if SSO RBAC is not enabled
  server/apiserver/argoserver.go
Labels: security, area/sso-rbac

#11627 fix: deprecated Link(Help-Contact) Issue
  ui/src/app/help/components/help.tsx
Labels: area/ui

#11632 feat(ui): retry workflows with parameter (#10824)
  ui/src/app/shared/services/workflows-service.ts
  ui/src/app/shared/workflow-operations-map.tsx
  ui/src/app/workflows/components/retry-workflow-panel.tsx
  ui/src/app/workflows/components/workflow-details/workflow-details.tsx
  ui/src/models/index.ts
  ui/src/models/resubmit-opts.ts
  ui/src/models/submit-opts.ts
Labels: area/ui

#11593 chore(deps): upgrade `monaco-editor` to 0.30
  ui/package.json
  ui/src/app/shared/components/object-editor/object-editor.tsx
  ui/src/app/workflows/components/workflow-details/artifact-panel.tsx
  ui/yarn.lock
Labels: dependencies, javascript

#11628 build(ui): upgrade to Webpack v5 + upgrade loaders + plugins
  ui/package.json
  ui/src/app/webpack.config.js
  ui/yarn.lock
Labels: dependencies, area/ui, javascript

#11630 chore(deps): remove unused JS deps
  ui/package.json
Labels: dependencies, area/ui, javascript

#11641 chore(deps): remove unneeded Yarn resolutions
  ui/package.json
  ui/yarn.lock
Labels: dependencies, area/ui, javascript

#11675 chore: update `manifests` to remove deprecation warnings
  manifests/namespace-install/kustomization.yaml
  manifests/quick-start/base/kustomization.yaml
  manifests/quick-start/minimal/kustomization.yaml
  manifests/quick-start/mysql/kustomization.yaml
  manifests/quick-start/postgres/kustomization.yaml
  manifests/quick-start/sso/dex/kustomization.yaml
  manifests/quick-start/sso/kustomization.yaml
  test/e2e/manifests/events/kustomization.yaml
  test/e2e/manifests/minimal/kustomization.yaml
  test/e2e/manifests/mixins/argo-server-cluster-workflow-template-rbac.yaml
  test/e2e/manifests/mixins/workflow-controller-cluster-workflow-template-rbac.yaml
  test/e2e/manifests/mysql/kustomization.yaml
  test/e2e/manifests/plugins/kustomization.yaml
  test/e2e/manifests/postgres/kustomization.yaml
  test/e2e/manifests/prometheus/kustomization.yaml
  test/e2e/manifests/sso/kustomization.yaml
  test/e2e/manifests/stress/kustomization.yaml
Labels: area/manifests

#11625 docs(cli): clarify the difference b/t `retry` and `resubmit`
  cmd/argo/commands/resubmit.go
  cmd/argo/commands/retry.go
  docs/cli/argo_resubmit.md
  docs/cli/argo_retry.md
Labels: area/cli

#11638 fix: ensure labels is defined before key access. Fixes #11602
  ui/src/app/workflows/components/workflows-row/workflows-row.tsx
Labels: area/ui

#11629 chore(ui): fix formatting errors in config
  ui/jest.config.js
  ui/src/app/webpack.config.js
Labels: area/ui, area/build

#11637 ci(deps): dedupe `yarn.lock`, add check for dupes
  .github/workflows/ci-build.yaml
  Makefile
  ui/package.json
  ui/yarn.lock
Labels: dependencies, area/ui, area/build, javascript

#11692 fix: Add missing new version modal for v3.5
  ui/src/app/modals/new-version/new-version-modal.tsx
Labels: area/ui

#11690 docs: Add notes on using pprof for development
  .spelling
  docs/running-locally.md
Labels: area/docs

#11710 chore(deps): update `monaco-editor` to latest 0.41.0
  ui/package.json
  ui/yarn.lock
Labels: dependencies, area/ui, javascript

#11709 docs: Add v3.5 upgrading notes
  docs/upgrading.md
Labels: area/docs

#11701 docs: moved the policy regarding commits from when it was running locally to the contributor page
  docs/CONTRIBUTING.md
  docs/running-locally.md
Labels: area/docs
