Repository argoproj/argo-workflows, pull requests merged in 2024-11, with the labels that each got.

#12611 refactor(deps): remove `moment` dep and usage
  ui/package.json
  ui/src/workflows/components/workflow-node-info/workflow-node-info.tsx
  ui/src/workflows/components/workflow-timeline/workflow-timeline.tsx
  ui/yarn.lock
Labels: type/dependencies, area/ui, javascript

#13790 feat: include container name in error message. Fixes #10007
  docs/upgrading.md
  test/e2e/cli_test.go
  workflow/controller/operator.go
Labels: area/controller

#12979 fix: consistently set executor log options
  util/cmd/glog.go
  workflow/controller/agent.go
  workflow/controller/artifact_gc.go
  workflow/controller/operator.go
  workflow/controller/operator_test.go
  workflow/controller/workflowpod.go
  workflow/controller/workflowpod_test.go
Labels: area/controller, area/executor, prioritized-review, area/agent

#13896 docs: fix refs to `stopStrategy.expression`
  api/jsonschema/schema.json
  api/openapi-spec/swagger.json
  docs/cron-workflows.md
  docs/fields.md
  pkg/apis/workflow/v1alpha1/cron_workflow_types.go
  pkg/apis/workflow/v1alpha1/generated.proto
  pkg/apis/workflow/v1alpha1/openapi_generated.go
  sdks/java/client/docs/IoArgoprojWorkflowV1alpha1CronWorkflowStatus.md
  sdks/python/client/argo_workflows/model/io_argoproj_workflow_v1alpha1_cron_workflow_status.py
  sdks/python/client/docs/IoArgoprojWorkflowV1alpha1CronWorkflowStatus.md
Labels: area/docs

#13734 fix: correct retry logic
  workflow/controller/operator_test.go
  workflow/util/util.go
  workflow/util/util_test.go
Labels: area/retry-manual

#13923 fix(ui): Clickable URLs are messing up formatting in the UI
  ui/src/shared/components/linkified-text.tsx
Labels: area/ui

#13915 fix(ui): improve editor performance and fix Submit button. Fixes #13892
  ui/src/cluster-workflow-templates/cluster-workflow-template-creator.tsx
  ui/src/cluster-workflow-templates/cluster-workflow-template-details.tsx
  ui/src/cluster-workflow-templates/cluster-workflow-template-editor.tsx
  ui/src/cron-workflows/cron-workflow-creator.tsx
  ui/src/cron-workflows/cron-workflow-details.tsx
  ui/src/cron-workflows/cron-workflow-editor.tsx
  ui/src/event-flow/event-flow-page.tsx
  ui/src/event-sources/event-source-creator.tsx
  ui/src/event-sources/event-source-details.tsx
  ui/src/event-sources/event-source-editor.tsx
  ui/src/sensors/sensor-creator.tsx
  ui/src/sensors/sensor-details.tsx
  ui/src/sensors/sensor-editor.tsx
  ui/src/shared/components/object-editor.tsx
  ui/src/shared/components/object-parser.ts
  ui/src/shared/components/resource-editor/resource-editor.tsx
  ui/src/shared/components/resource-editor/resource.scss
  ui/src/shared/use-editable-object.test.ts
  ui/src/shared/use-editable-object.ts
  ui/src/workflow-event-bindings/workflow-event-bindings.tsx
  ui/src/workflow-templates/workflow-template-creator.tsx
  ui/src/workflow-templates/workflow-template-details.tsx
  ui/src/workflow-templates/workflow-template-editor.tsx
  ui/src/workflows/components/workflow-creator.tsx
  ui/src/workflows/components/workflow-details/workflow-resource-panel.tsx
  ui/src/workflows/components/workflow-editor.tsx
  ui/src/workflows/components/workflow-yaml-viewer/workflow-yaml-viewer.tsx
Labels: area/ui

#13921 fix: consistent variable substitution for `configMapKeyRef`. Fixes #13890
  test/e2e/hooks_test.go
  workflow/common/util.go
  workflow/common/util_test.go
Labels: area/templating

#13685 build(docs): set `site_url` from ReadTheDocs env var
  mkdocs.yml
Labels: area/docs, area/build, prioritized-review

#13812 docs: update `examples/README.md` to its current usage
  examples/README.md
Labels: area/docs

#13672 perf: Add workflow template informer to server
  Makefile
  pkg/apiclient/apiclient.go
  pkg/apiclient/argo-kube-client.go
  server/apiserver/argoserver.go
  server/clusterworkflowtemplate/cluster_workflow_template_server.go
  server/clusterworkflowtemplate/cluster_workflow_template_server_test.go
  server/clusterworkflowtemplate/informer.go
  server/clusterworkflowtemplate/wf_client_store.go
  server/cronworkflow/cron_workflow_server.go
  server/cronworkflow/cron_workflow_server_test.go
  server/types/store.go
  server/workflow/workflow_server.go
  server/workflow/workflow_server_test.go
  server/workflowtemplate/informer.go
  server/workflowtemplate/wf_client_store.go
  server/workflowtemplate/workflow_template_server.go
  server/workflowtemplate/workflow_template_server_test.go
  test/e2e/argo_server_benchmark_test.go
  test/e2e/argo_server_test.go
  test/e2e/benchmarks/multiple-ref-echo-1-workflowtemplate.yaml
  test/e2e/benchmarks/multiple-ref-echo-2-workflowtemplate.yaml
  test/e2e/benchmarks/multiple-ref-main-workflowtemplate.yaml
Labels: area/server

#13942 chore: promotions from membership meeting (Nov 2024)
  CODEOWNERS
  OWNERS
Labels: area/contributing
