Repository argoproj/argo-workflows, pull requests merged in 2024-12, with the labels that each got.

#13715 test: simple DB CLI for local development
  docs/running-locally.md
  hack/db/main.go
Labels: area/build, area/workflow-archive, area/contributing

#11707 fix: replace deprecated `bouk/staticfiles` with native Go `embed`. fixes #11654
  .github/workflows/ci-build.yaml
  .golangci.yml
  Makefile
  dev/nix/conf.nix
  dev/nix/flake.nix
  server/apiserver/argoserver.go
  server/static/files.go
  server/static/files.go.stub
  server/static/response-rewriter.go
  server/static/static.go
  server/static/static_test.go
  ui/embed.go
Labels: type/dependencies, go, type/tech-debt

#13976 fix(ci): snyk scan
  .github/workflows/snyk.yml
Labels: area/contributing

#13930 fix(ui): improve markdown styles for workflow-row, workflow-templates, cluster-workflow-templates, and cron-workflows
  docs/assets/title-and-description-markdown-cluster-workflow-template.png
  docs/assets/title-and-description-markdown-complex-workflow.png
  docs/assets/title-and-description-markdown-cron-workflow.png
  docs/assets/title-and-description-markdown-workflow-drawer.png
  docs/assets/title-and-description-markdown-workflow-template.png
  docs/title-and-description.md
  ui/src/cluster-workflow-templates/cluster-workflow-template-list.scss
  ui/src/cluster-workflow-templates/cluster-workflow-template-markdown.scss
  ui/src/cluster-workflow-templates/cluster-workflow-template-markdown.tsx
  ui/src/cron-workflows/cron-workflow-list.scss
  ui/src/cron-workflows/cron-workflow-row.scss
  ui/src/cron-workflows/cron-workflow-row.tsx
  ui/src/shared/components/workflows-utils.test.ts
  ui/src/workflow-templates/workflow-template-list.scss
  ui/src/workflow-templates/workflow-template-row.scss
  ui/src/workflow-templates/workflow-template-row.tsx
  ui/src/workflows/components/workflow-drawer/workflow-drawer.scss
  ui/src/workflows/components/workflow-drawer/workflow-drawer.tsx
  ui/src/workflows/components/workflows-list/workflows-list.scss
  ui/src/workflows/components/workflows-row/workflows-row.scss
  ui/src/workflows/components/workflows-row/workflows-row.tsx
  ui/src/workflows/utils.ts
Labels: area/ui

#13922 feat(ui): prefill parameters for workflow submit form. Fixes #12124
  ui/src/cluster-workflow-templates/cluster-workflow-template-details.tsx
  ui/src/shared/get_workflow_params.test.ts
  ui/src/shared/get_workflow_params.ts
  ui/src/shared/history.ts
  ui/src/workflow-templates/workflow-template-details.tsx
  ui/src/workflows/components/submit-workflow-panel.tsx
  ui/src/workflows/components/workflow-creator.tsx
  ui/src/workflows/components/workflows-list/workflows-list.tsx
Labels: area/ui

#13978 fix: mark all its children(container) as deleted if pod deleted. Fixes #13951
  workflow/controller/operator.go
  workflow/controller/operator_test.go
Labels: area/controller

#13819 fix: further optimize archive workflow listing. Fixes #13601
  Makefile
  persist/sqldb/migrate.go
  persist/sqldb/workflow_archive.go
Labels: area/api, area/workflow-archive, prioritized-review

#13827 fix: ensure that nodes complete when workflow fails with `parallelism` and `failFast`. Fixes #13806
  test/e2e/expectedfailures/parallelism-dag-fail-fast.yaml
  test/e2e/expectedfailures/parallelism-dag-failure.yaml
  test/e2e/expectedfailures/parallelism-step-fail-fast.yaml
  test/e2e/expectedfailures/parallelism-step-failure.yaml
  test/e2e/functional_test.go
  workflow/controller/operator.go
Labels: area/controller, prioritized-review, area/parallelism

#13642 fix: respect `workflowDefaults` when validating workflows. Fixes #10946. Fixes #11465
  pkg/apiclient/argo-kube-client.go
  pkg/apiclient/offline-cluster-workflow-template-service-client.go
  pkg/apiclient/offline-cron-workflow-service-client.go
  pkg/apiclient/offline-workflow-service-client.go
  pkg/apiclient/offline-workflow-template-service-client.go
  server/apiserver/argoserver.go
  server/clusterworkflowtemplate/cluster_workflow_template_server.go
  server/clusterworkflowtemplate/cluster_workflow_template_server_test.go
  server/cronworkflow/cron_workflow_server.go
  server/cronworkflow/cron_workflow_server_test.go
  server/workflow/workflow_server.go
  server/workflow/workflow_server_test.go
  server/workflowarchive/archived_workflow_server.go
  server/workflowarchive/archived_workflow_server_test.go
  server/workflowtemplate/workflow_template_server.go
  test/e2e/manifests/mixins/workflow-controller-configmap.yaml
  test/e2e/testdata/workflow-template-sub-test.yaml
  test/e2e/workflow_template_test.go
  workflow/controller/controller.go
  workflow/controller/operator.go
  workflow/cron/controller.go
  workflow/cron/operator.go
  workflow/util/util.go
  workflow/util/util_test.go
  workflow/validate/testdata/workflow-template-sub-test-1.yaml
  workflow/validate/testdata/workflow-template-sub-test-2.yaml
  workflow/validate/testdata/workflow-template-sub-test-3.yaml
  workflow/validate/validate.go
  workflow/validate/validate_test.go
Labels: area/api, area/server

#13933 feat: support archive logs in resource template. Fixes:#9900
  cmd/argoexec/commands/resource.go
  cmd/argoexec/commands/wait.go
  test/e2e/artifacts_test.go
  workflow/controller/workflowpod.go
  workflow/executor/executor.go
Labels: area/templates/resource, area/archive-logs

#13935 feat: Allow markdown title and description in KeyValueEditor
  ui/src/shared/components/editors/key-value-editor.scss
  ui/src/shared/components/editors/key-value-editor.tsx
  ui/src/shared/components/editors/labels-and-annotations-editor.tsx
  ui/src/shared/components/editors/workflow-parameters-editor.tsx
Labels: area/ui
