Repository argoproj/argo-workflows, pull requests merged in 2025-03, with the labels that each got.

#14264 chore(deps): fix snyk
  go.mod
  go.sum
Labels: type/dependencies

#14273 docs: fix kubernetes versions (release-3.6)
  Makefile
  docs/tested-kubernetes-versions.md
Labels: area/docs

#14274 docs: fix kubernetes versions
  Makefile
Labels: area/docs

#14321 fix(workflow/sync): use RWMutex to prevent concurrent map access
  workflow/sync/sync_manager.go
Labels: area/mutex-semaphore
