Repository argoproj/argo-workflows, pull requests merged in 2025-05, with the labels that each got.

#13747 fix(sso): use relative redirect URLs. Fixes #13031
  server/auth/sso/sso.go
  server/auth/sso/sso_test.go
  ui/src/login/login.tsx
  ui/src/shared/base.ts
  ui/src/shared/services/requests.ts
Labels: type/security, area/ui, area/sso-rbac, prioritized-review

#14467 fix: correctly release all mutexes when multiple mutexes are held. FIxes #14461
  workflow/sync/sync_manager.go
  workflow/sync/sync_manager_test.go
Labels: area/mutex-semaphore

#13883 feat: mark memoized node as cached
  ui/src/shared/components/graph/icon.tsx
  ui/src/workflows/components/workflow-dag/icons.ts
  ui/src/workflows/components/workflow-dag/workflow-dag.tsx
Labels: area/ui

#14341 build: add CI to pre-build and validate dev container
  .devcontainer/builder/Dockerfile
  .devcontainer/builder/devcontainer-lock.json
  .devcontainer/builder/devcontainer.json
  .devcontainer/devcontainer.json
  .devcontainer/pre-build.sh
  .github/workflows/devcontainer.yaml
  Makefile
  docs/running-locally.md
Labels: area/contributing

#14446 feat!: Introduce curated Sprig function allowlist
  .spelling
  docs/upgrading.md
  docs/variables.md
  server/event/dispatch/operation_test.go
  test/e2e/testdata/workflow-template-with-resource-expr.yaml
  util/expr/env/env.go
  util/expr/env/env_test.go
  util/template/replace_test.go
  workflow/controller/controller_test.go
  workflow/controller/operator_concurrency_test.go
  workflow/controller/operator_test.go
  workflow/controller/testdata/workflow-sub-test-6.yaml
  workflow/validate/validate_test.go
Labels: type/feature, type/tech-debt, area/templating
