Repository argoproj/argo-workflows, pull requests merged in 2025-07, with the labels that each got.

#14491 feat: new-features automated documentation
  .features/TEMPLATE.md
  .features/pending/feat-notes.md
  .github/workflows/ci-build.yaml
  .github/workflows/pr.yaml
  .gitignore
  .spelling
  Makefile
  docs/releasing.md
  docs/running-locally.md
  hack/featuregen/components.go
  hack/featuregen/contents.go
  hack/featuregen/contents_test.go
  hack/featuregen/main.go
  hack/featuregen/main_test.go
Labels: area/contributing

#14636 fix: do PR check with some depth for merge-base
  .github/workflows/pr.yaml
Labels: area/contributing

#14640 fix: fix for feature note changed files
  .github/workflows/pr.yaml
Labels: area/contributing

#14619 fix: Make codegen easier to understand when it fails
  Makefile
Labels: area/contributing

#14644 chore: remove more log levels and implement speedups
  cmd/argo/commands/root.go
  cmd/workflow-controller/main.go
  docs/upgrading.md
  pkg/apis/workflow/v1alpha1/workflow_types.go
  server/apiserver/argoserver.go
  util/cmd/cmd.go
  util/cmd/log.go
  util/env/env.go
  util/errors/errors.go
  util/file/fileutil.go
  util/logging/logging.go
  util/logging/slog.go
  util/logging/test_hook.go
  workflow/controller/artifact_gc.go
  workflow/controller/controller.go
  workflow/controller/dag.go
  workflow/controller/operator.go
  workflow/controller/steps.go
  workflow/controller/taskset.go
  workflow/controller/workflowpod.go
  workflow/cron/controller.go
  workflow/gccontroller/gc_controller.go
Labels: area/telemetry/logs

#14696 fix: GC realtime metrics after workflow completed. Fixes #14694
  workflow/controller/controller.go
  workflow/controller/operator.go
  workflow/metrics/metrics_custom.go
  workflow/metrics/metrics_test.go
Labels: prioritized-review
